### ISSUE TITLE
TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by a-damC** [insapathogenomics/ReporTree#12]
### reportree options used (Hierarchical clustering):
```
python ~/Downloads/ReporTree/reportree.py -m ../meta_data_for_reportree_II.tsv -a ../results_alleles.tsv -out output_HC_analysis --HC-threshold single-0-28 --partitions2report all --analysis HC
```

### Standard output
```
******************** running reportree.py ********************

version 2.0.0 last updated on 2023-03-28

/home/phe.gov.uk/adam.crewdson/Downloads/ReporTree/reportree.py -m ../meta_data_for_reportree_II.tsv -a ../results_alleles.tsv -out output_HC_analysis --HC-threshold single-0-28 --partitions2report all --analysis HC
start: 2023-03-29 15:16:05.601926

Profiles file provided -> will run partitioning_HC.py:


-------------------- partitioning_HC.py --------------------

version 1.2.0 last updated on 2023-03-28 

/home/phe.gov.uk/adam.crewdson/Downloads/ReporTree/scripts/partitioning_HC.py -a ../results_alleles.tsv -o output_HC_analysis --HC-threshold single-0-28 -d 1.0 --site-inclusion 0.0 --loci-called 0.0 --missing-code 0 --pct-HC-threshold none 

Profile matrix provided... pairwise distance will be calculated!
Getting the pairwise distance matrix with cgmlst-dists (if your profile matrix is too big, this will be done in chunks of 2000 alleles/positions)...
This is cgmlst-dists 0.4.0
Loaded 56 samples x 1023 allele calls
Calculating distances: 100.00%
Writing distance matrix to stdout...

Done.
	Getting condensed distance matrix...
Hierarchical clustering with method: single...
	Maximum distance 22.0...
	Generating newick file...
	Defining clusters...
	Calculating clustering in range 0 22.0 with a distance of 1.0
Traceback (most recent call last):
  File "/home/phe.gov.uk/adam.crewdson/Downloads/ReporTree/scripts/partitioning_HC.py", line 749, in <module>
    main()
  File "/home/phe.gov.uk/adam.crewdson/Downloads/ReporTree/scripts/partitioning_HC.py", line 629, in main
    for thr in range(min_thr,max_thr):
TypeError: 'str' object cannot be interpreted as an integer
```

I used range 0-28 for clustering.
The max number of clusters is 22 (as provided by `Maximum distance 22.0...`) and this is where the error is born.
When I change my range to 0-21 it works.

I think it would be useful to have something like [line 657](https://github.com/insapathogenomics/ReporTree/blob/88698f714628a7ec9131d644dd821c57e0d55f7d/scripts/partitioning_HC.py#L657) somewhere in the indent at 616 or to have an option where you cluster from 0-max as you may not know what clustering will look like beforehand.
In pHierCC it allows you to cluster beyond the max and all isolates converge into one cluster please see attached files of pHierCC output and reportree from my own data.
[230328_example_HierCC.xlsx](https://github.com/insapathogenomics/ReporTree/files/11102319/230328_example_HierCC.xlsx)
[230329_example_reportree.xlsx](https://github.com/insapathogenomics/ReporTree/files/11102328/230329_example_reportree.xlsx)
*Shortened cluster_ to C_ and Singleton to S_ in the reportree file*

If you need anymore info let me know!
Thanks for such an all encompassing programme

**Comment by vmixao** [comment]
Dear @a-damC,

Thank you for your interest in ReporTree and for your feedback. 

The issue you found in the range option when the maximum possible distance is lower than the maximum value provided is solved. Thanks for reporting it!

Regarding your suggestion, actually, this is already implemented in ReporTree. As mentioned in the help, to get clustering at all possible thresholds for a given HC method (so, from 0 to max), you just need to write the method name, without any threshold. So, in your command line it would be ‘--HC-threshold single’. 

Please note that this is the default behavior of ReporTree. So, if you want to get your clusters at all possible thresholds either with single-linkage or with a grapetree method, you do not need to mention any threshold in the command line. 

Please let us know if you need any help or clarifications.

Kind regards,
Verónica
